services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - ${INFLUX_PATH}:/var/lib/influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: always
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ${GRAFANA_PATH}:/var/lib/grafana
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    volumes:
      - ${MOSQUITTO_CONFIG}:/mosquitto/config
      - ${MOSQUITTO_DATA}:/mosquitto/data
      - ${MOSQUITTO_LOG}:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001